{% set name = "lenstest" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lenstest-{{ version }}.tar.gz
  sha256: 5249d32e9e429d9d99c95b95a7f32feceac7e2549d01ce91f08c15d3cc1d8eda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - lenstest
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/test_foucault.py
    - tests/test_lenstest.py
    - tests/test_ronchi.py

  commands:
    - pytest tests/test_foucault.py
    - pytest tests/test_lenstest.py
    - pytest tests/test_ronchi.py

about:
  home: https://github.com/scottprahl/lenstest
  summary: |
    A collection of routines for non-interferometric testing of lenses and 
    mirrors.  This implementation contains code for the Foucault Knife Edge Test
    and Ronchi Ruling Test.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://lenstest.readthedocs.io/
  dev_url: https://github.com/scottprahl/lenstest

extra:
  recipe-maintainers:
    - scottprahl
